<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="QB-CLT-1378" failures="1" tests="3" name="Surefire test" time="6.341" errors="0" timestamp="2023-01-23T21:54:27 IST">
  <testcase classname="SeleniumAutomation.TestCases.LoginTest" name="login_with_invalid_credentials" time="0.32">
    <failure type="java.lang.AssertionError" message="expected [Epi2c sadface: Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epi2c sadface: Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at SeleniumAutomation.TestCases.LoginTest.login_with_invalid_credentials(LoginTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- login_with_invalid_credentials -->
  <testcase classname="SeleniumAutomation.TestCases.LoginTest" name="login_with_valid_credentials" time="0.392"/>
  <testcase classname="SeleniumAutomation.TestCases.SubmitOrderTest" name="user_submit_new_order" time="0.964"/>
</testsuite> <!-- Surefire test -->
