<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="QB-CLT-1378" failures="1" tests="3" name="Purchse product" time="6.748" errors="0" timestamp="2023-01-24T09:14:11 IST">
  <testcase classname="SeleniumAutomation.TestCases.SubmitOrderTest" name="user_submit_new_order" time="1.132"/>
  <testcase classname="SeleniumAutomation.TestCases.LoginTest" name="login_with_invalid_credentials" time="0.28">
    <failure type="java.lang.AssertionError" message="expected [Epi2c sadface: Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epi2c sadface: Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at SeleniumAutomation.TestCases.LoginTest.login_with_invalid_credentials(LoginTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login_with_invalid_credentials -->
  <testcase classname="SeleniumAutomation.TestCases.LoginTest" name="login_with_valid_credentials" time="0.43"/>
</testsuite> <!-- Purchse product -->
